name: Nix
description: Run commands in nix-shell
author: https://github.com/kreisys
requirements:
  - nix
  - nix-shell
configuration:
  properties:
    no-pure:
      type: boolean
    skip-shell:
      type: boolean
    binary-cache:
      type: string
  required:
    - binary-cache
